/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.chatbot;

import java.net.URI;
import java.sql.*;
import main.chatbot.LinkedList.Node;
import main.chatbot.OpenURL;

/**
 *
 * @author Admin
 */
public class QuickButton extends javax.swing.JFrame {

    /**
     * Creates new form QuickButton
     */
    public QuickButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        Connection conn;
        Statement stmt;

        ResultSet rs;
        try{
            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chatbot", "root", "");

            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM `linked` WHERE 1 ORDER BY `count` DESC");
            int i=0;
            while(rs.next()){
                //             stmt.executeUpdate("UPDATE `linked` SET `count`="+current.count+" WHERE `url`='"+current.name+"';");
                if(i==0){
                    jButton1.setText(rs.getString(1));
                    i++;break;
                }
            }}catch(Exception e){
                System.out.println(e);
            }
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("jButton2");
            try{
                Class.forName("com.mysql.jdbc.Driver");

                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chatbot", "root", "");

                stmt = conn.createStatement();
                rs = stmt.executeQuery("SELECT * FROM `linked` WHERE 1 ORDER BY `count` DESC");
                int i=0;
                while(rs.next()){
                    //             stmt.executeUpdate("UPDATE `linked` SET `count`="+current.count+" WHERE `url`='"+current.name+"';");
                    if(i==1){
                        jButton2.setText(rs.getString(1));

                        break;
                    }i++;
                }}catch(Exception e){
                    System.out.println(e);
                }
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                    }
                });

                jButton3.setText("jButton3");
                try{
                    Class.forName("com.mysql.jdbc.Driver");

                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chatbot", "root", "");

                    stmt = conn.createStatement();
                    rs = stmt.executeQuery("SELECT * FROM `linked` WHERE 1 ORDER BY `count` DESC");
                    int i=0;
                    while(rs.next()){
                        //             stmt.executeUpdate("UPDATE `linked` SET `count`="+current.count+" WHERE `url`='"+current.name+"';");
                        if(i==2){
                            jButton3.setText(rs.getString(1));

                            break;
                        }i++;
                    }}catch(Exception e){
                        System.out.println(e);
                    }

                    jButton4.setText("jButton4");
                    jButton4.setText("AHMEDABAD UNIVERSITY");
                    jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton4ActionPerformed(evt);
                        }
                    });

                    jButton5.setText("jButton5");
                    jButton5.setText("AURIS");
                    jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton5ActionPerformed(evt);
                        }
                    });

                    jButton6.setText("jButton6");
                    jButton6.setText("DSA LAB");
                    jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton6ActionPerformed(evt);
                        }
                    });

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jButton4))
                            .addGap(209, 209, 209)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addComponent(jButton5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3)
                                .addComponent(jButton6))
                            .addGap(90, 90, 90))
                    );
                    layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton2)
                                .addComponent(jButton3))
                            .addGap(142, 142, 142)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(jButton5)
                                .addComponent(jButton6))
                            .addContainerGap(475, Short.MAX_VALUE))
                    );

                    pack();
                }// </editor-fold>//GEN-END:initComponents

 class Node{
    int count;
    String name;
    Node next;
    
    Node(int count,String name){
        this.count=count;
        this.name=name;
        this.next=null;
    }
    
}
public static Node head=null;
public static Node tail=null;
public static int size=0;


 void get(){
Node current=head;
         Connection conn;  
  
   Statement stmt;

   ResultSet rs;
   try{        
   Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chatbot", "root", "");

            stmt = conn.createStatement();

            rs = stmt.executeQuery("SELECT * FROM `linked` WHERE 1");
   
while(rs.next()){
System.out.println(rs.getString(1));    
insert(Integer.parseInt(rs.getString(2)),rs.getString(1));
}

   }catch(Exception e){
       System.out.println("1"+e);
   }     
}

 void insert(int count,String name){
    Node newnode=new Node(count,name);
    if(head==null){
        head=newnode;
        tail=newnode;
    }
    else{
        tail.next=newnode;
        tail=newnode;
    }
    size++;
    sort();
}
    static void sort(){
        if (head==null){
            System.out.println("Not performed");
            return;
        }
        else{
            String arr_name[]=new String[size];
            int arr_number[]=new int[size];
            int i2=0;
            Node current=head;
            while(current!=null){
                arr_name[i2]=current.name;
                arr_number[i2]=current.count;
                i2++;
                current=current.next;
            }
            for (int i = 0; i < size; i++) {
                for (int j = i+1; j < size; j++) {
                    if(arr_number[i]<arr_number[j]){
                        System.out.println("Yes");
                        String temp=arr_name[i];
                        arr_name[i]=arr_name[j];
                        arr_name[j]=temp;
                        
                        int temp2=arr_number[i];
                        arr_number[i]=arr_number[j];
                        arr_number[j]=temp2;
                    }
                }
            }
            
            
            Node current2=head;
            int m=0;
            while(current2!=null){
                current2.name=arr_name[m];
                current2.count=arr_number[m];
                m++;
                current2=current2.next;
            }
        }
    }
     void display(){
        Node current=head;
        while(current!=null){
            System.out.println("Name : "+current.name);
            System.out.println("Number : "+current.count);
            
            System.out.println("");
                    current=current.next;
        }
    }
     void search(String name){
        if(head==null){
            System.out.println("Not Found");
//            return 0;
        }
        else{
            boolean flag=false;
            Node current=head;
            while(current!=null){
                if(name.equals(current.name)){
                    System.out.println("Found!");
                    System.out.println("Name:"+current.name);
                    System.out.println("Number:"+current.count);
                    current.count++;
                    flag=true;
//                return current.count;
                }
                current=current.next;
            }
            if(!flag){
            System.out.println("Not found");
                insert(0, name);
            }
//        return 0;
        }
    }
    static void add(){
            Connection conn;  
  Node current=head;
   Statement stmt;

   ResultSet rs;
   try{        
   Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chatbot", "root", "");

            stmt = conn.createStatement();
while(current!=null){
             stmt.executeUpdate("UPDATE `linked` SET `count`="+current.count+" WHERE `url`='"+current.name+"';");
current=current.next;
}
   }catch(Exception e){
       System.out.println(e);
   }
    }
   void countinc(String name){
            Node current=head;
            while(current!=null){
                if(name.equals(current.name)){
                    System.out.println("Found!");
                    System.out.println("Name:"+current.name);
                    current.count++;
                    System.out.println("Number:"+current.count);
                    return;
                }
                current=current.next;
        }
            
            System.out.println("Not found");
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      LinkedList l=new LinkedList();
        l.get();
        String str=jButton1.getText();
        try{
            String strm = str;
            
            URI uri = new URI("http://"+ strm + ".com");
            l.search(strm);
//            l.countinc(strm);
            java.awt.Desktop.getDesktop().browse(uri);
            System.out.println("Website Opened in your default browser.");
        l.display();
        l.add();
        }
        catch(Exception e){
            e.printStackTrace();
        }  
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      LinkedList l=new LinkedList();
        l.get();
        String str=jButton2.getText();
        try{
            String strm = str;
            
            URI uri = new URI("http://"+ strm + ".com");
            l.search(strm);
//            l.countinc(strm);
            java.awt.Desktop.getDesktop().browse(uri);
            System.out.println("Website Opened in your default browser.");
        l.display();
        l.add();
        }
        catch(Exception e){
            e.printStackTrace();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
           
            
            URI uri = new URI("https://ahduni.edu.in/");
//            l.search(strm);
//            l.countinc(strm);
            java.awt.Desktop.getDesktop().browse(uri);
            System.out.println("Website Opened in your default browser.");
//        l.display();
//        l.add();
        }
        catch(Exception e){
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try{
           
            
            URI uri = new URI("https://auris.ahduni.edu.in/core-emli/code/my_home/");
//            l.search(strm);
//            l.countinc(strm);
            java.awt.Desktop.getDesktop().browse(uri);
            System.out.println("Website Opened in your default browser.");
//        l.display();
//        l.add();
        }
        catch(Exception e){
            e.printStackTrace();
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      try{
           
            
            URI uri = new URI("https://sites.google.com/ahduni.edu.in/dsalab2019/");
//            l.search(strm);
//            l.countinc(strm);
            java.awt.Desktop.getDesktop().browse(uri);
            System.out.println("Website Opened in your default browser.");
//        l.display();
//        l.add();
        }
        catch(Exception e){
            e.printStackTrace();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
}
