/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbot;

import AppPackage.AnimationClass;
import java.awt.*;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Caret;
import javafx.animation.*;
import javax.swing.Timer;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.Utilities;
//import AnimationClass.*;

/**
 *
 * @author Admin
 */

public class TextArea extends javax.swing.JFrame {

    /**
     * Creates new form TextArea
     */
    public TextArea() throws BadLocationException {
        initComponents(); 
         this.setSize(1062, 744);
        this.setVisible(true);
//        initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/chatbot/oie_30144137iJGmGE90.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 350, 690, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/chatbot/loading.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(720, 470, 260, 170);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(910, 430, 79, 25);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 410, 210, 80);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 370, 130, 70);

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 40, 950, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int z2=0;
        Timer t2=new Timer(500,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                z2++;
        if(z2==8){
              jLabel1.setVisible(false);
        }        
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseReleased
int z=0;
Icon a=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-210620__01.jpg");
Icon b=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-211644.jpg");
Icon c=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\DSA Lab\\AULOGO\\\\Transparent\\3.png");
Icon d=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-211644.jpg");
Icon e2=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-210620__01.jpg");
Icon a3=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\DSA Lab\\AULOGO\\Transparent\\1.png");
Icon b3=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-211644.jpg");
Icon c3=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-210620__01.jpg");
Icon d3=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-211644.jpg");
Icon e3=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-210620__01.jpg");
Timer t=new Timer(250, new ActionListener()
{public void actionPerformed(ActionEvent e){

            z++;
            switch(z){
                case 1:{
                 jLabel1.setIcon(a);
                 jLabel3.setIcon(a);
                 break;
                }
                case 2:{
                 jLabel1.setIcon(b);
                 jLabel3.setIcon(b);
                 break;
                }
                case 3:{
                 jLabel1.setIcon(c);
                 jLabel3.setIcon(c);
                 break;
                }
                case 4:{
                 jLabel1.setIcon(d);
                 jLabel3.setIcon(d);
                 break;
                }
                case 5:{
                 jLabel1.setIcon(e2);
                 jLabel3.setIcon(e2);
                 break;
                }case 6:{
                 jLabel1.setIcon(a);
                 jLabel3.setIcon(a);
                 break;
                }
                case 7:{
                 jLabel1.setIcon(b);
                 jLabel3.setIcon(b);
                 break;
                }
                case 8:{
                 jLabel1.setIcon(c);
                 jLabel3.setIcon(c);
                 break;
                }
                case 9:{
                 jLabel1.setIcon(d);
                 jLabel3.setIcon(d);
                 break;
                }
                case 10:{
                 jLabel1.setIcon(e2);
                 jLabel3.setIcon(e2);
                 break;
                }case 11:{
                 jLabel1.setIcon(a);
                 jLabel3.setIcon(a);
                 break;
                }
                case 12:{
                 jLabel1.setIcon(b);
                 jLabel3.setIcon(b);
                 break;
                }
                case 13:{
                 jLabel1.setIcon(c);
                 jLabel3.setIcon(c);
                 break;
                }
                case 14:{
                 jLabel1.setIcon(d);
                 jLabel3.setIcon(d);
                 break;
                }
                case 15:{
                 jLabel1.setIcon(e2);
                 jLabel3.setIcon(e2);
                 break;
                }case 16:{
                 jLabel1.setIcon(a);
                 jLabel3.setIcon(a);
                 break;
                }
                case 17:{
                 jLabel1.setIcon(b);
                 jLabel3.setIcon(b);
                 break;
                }
                case 18:{
                 jLabel1.setIcon(c);
                 jLabel3.setIcon(c);
                 break;
                }
                case 19:{
                 jLabel1.setVisible(false);
                 jLabel3.setVisible(false);
                 break;
                }
            }
//            if(z==5){
//                System.exit(0);
//            }
        }
});
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            jLabel1.setLocation(860,330);
            jLabel2.setLocation(70,330);
            jLabel3.setLocation(370,330);
            StyledDocument doc=jTextPane1.getStyledDocument();
            SimpleAttributeSet left=new SimpleAttributeSet();
            StyleConstants.setAlignment(left, StyleConstants.ALIGN_LEFT);
            StyleConstants.setForeground(left, Color.red);
            SimpleAttributeSet Right=new SimpleAttributeSet();
            StyleConstants.setAlignment(Right, StyleConstants.ALIGN_RIGHT);
            StyleConstants.setForeground(Right, Color.blue);
            
            doc.insertString(doc.getLength(),"\nYOU:HELO",Right);
            doc.setParagraphAttributes(doc.getLength(), 1, Right, false);
            
            
            Caret e=jTextPane1.getCaret();
            Rectangle rect =jTextPane1.getUI().modelToView(jTextPane1, e.getDot());
            System.out.println(rect.toString());
            AnimationClass AC=new AnimationClass();
            Icon a=new ImageIcon("C:\\Users\\Admin\\Desktop\\seas ict\\Semester 3\\Heritage\\Screenshot_20190828-211644.jpg");
//            jLabel2.setIcon(a);
            jLabel1.setIcon(a);
              doc.insertString(doc.getLength(),"\n\nALICE:HOLA",left);
            doc.setParagraphAttributes(doc.getLength(), 1, left, false);  
              AC.jLabelYUp(jLabel1.getY(), jTextPane1.getY()+rect.y+70, 10, 2, jLabel1);
              
//            jLabel1.setVisible(false);
                
t.start();

//          t.start();
//         AC.jLabelYUp(jLabel2.getY(), jTextArea2.getY()+rect2.y+70, 10, 2, jLabel2);
//            jLabel1.setLocation(p);

AC.jLabelYUp(jLabel3.getY(), jTextPane1.getY()+rect.y+70, 1, 2, jLabel3);
            AC.jLabelXLeft(jLabel3.getX(),jLabel2.getX(), 10, 2, jLabel3);
//System.out.println("Lines"+countLines());            
//init2Components(rect);
            
            
//            AC.jLabelYUp(jLabel2.getY(),jTextPane1.getY()+rect.y+70, 10, 2, jLabel1);
//            jTextArea1.setText(jTextArea1.getText()+"\n");
//            jTextArea2.setText(jTextArea2.getText()+"\n");

// TODO add your handling code here:
        } catch (BadLocationException ex) {
            Logger.getLogger(TextArea.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TextArea().setVisible(true);
                } catch (BadLocationException ex) {
                    Logger.getLogger(TextArea.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
 public void init2Components(Rectangle r){
        jLabel1.setLocation(860,330);
        jLabel1.setBackground(Color.YELLOW);
        jLabel1.setOpaque(true);
        
        //Move every (approx) 5 milliseconds        
        Timer t= new Timer(1, new ActionListener(){  
            @Override
            public void actionPerformed(ActionEvent e){
                //Move 1 px everytime
                z=jLabel1.getLocation().y-r.y;
                   
                jLabel1.setLocation(jLabel1.getLocation().x, jLabel1.getLocation().y-1);
                
                if(z>100 && z<200){
                    jLabel1.setIcon(a);
                }else if(z>200&& z<300){
                    jLabel1.setIcon(b);
                }else if(z>300&& z<400){
                    jLabel1.setIcon(b);
                }
                else{
                    jLabel1.setOpaque(false);
            
            }
                
//                System.out.println(jLabel1.getLocation().y+"y");


//                  System.out.println(r.y+"r.y");
//                System.out.println(z+"z");
                
                 
            }               
        });     
        jButton1.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                   if(!t.isRunning()) t.start();
                   else t.stop();
            }   
        }); 
    }
 public int countLines(){
     int totalCharacters=jTextPane1.getText().length();
     int linecount=(totalCharacters==0) ? 1:0;
     
     try{
         int offset=totalCharacters;
         while(offset>0){
             offset=Utilities.getRowStart(jTextPane1, offset)-1;
             linecount++;
         }
     }
     catch(Exception e){
         System.out.println(e);
     }
     return linecount;
 }
}

